sign-tag = false
push = true
tag-prefix = ""
consolidate-commits = true
pre-release-commit-message = "chore(release): {{version}}"
pre-release-replacements = []

[workspace]
independent-versioning = false

[hooks]
pre-release = [
  "cargo fmt --all -- --check",
  "cargo clippy --workspace --all-targets --all-features -D warnings",
  "cargo test --workspace --all-features",
]
post-release = [
  "git push --follow-tags",
]
