[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
unsound = "deny"

[licenses]
allow = [
    "MIT-0",
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
]
deny = []
copyleft = "warn"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
