[package]
name = "dbg-gdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

# Optional: gdbstub could be added later when wiring actual target

