name: MSRV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.79.0
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --workspace --no-default-features
      - name: Test
        run: cargo test --workspace --no-default-features

